apiVersion: v1
kind: Service
metadata:
  namespace: assigment
  creationTimestamp: null
  labels:
    app: api
  name: back
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: api
status:
  loadBalancer: {}
