apiVersion: v1
data:
  SQLALCHEMY_DATABASE_URI: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: back-secret
  namespace: assigment
