apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: assigment
  name: data
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: vasyldocker/quotes-data:v1
          name: db
          envFrom:
            - secretRef:  
                name: data-secret
          volumeMounts:    
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: storage
          ports:
          - containerPort: 3306
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: claim  
      restartPolicy: Always

