apiVersion: v1
kind: Service
metadata:
  namespace: assigment
  creationTimestamp: null
  labels:
    app: front
  name: front
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app: front
status:
  loadBalancer: {}
