apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: assigment
  name: sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: assigment
  name: claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: sc
